
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author h_lah
 */
public class WorkingGUI extends javax.swing.JFrame {

    /**
     * Creates new form Gui
     */
    public WorkingGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_registro = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_usernameRegister = new javax.swing.JTextField();
        pf_passwordRegister = new javax.swing.JPasswordField();
        rb_participante = new javax.swing.JRadioButton();
        rb_administrador = new javax.swing.JRadioButton();
        bt_registrarUsusario = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jd_admin = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        bt_salirAdmin = new javax.swing.JButton();
        bt_toCrearTorneo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_torneosAdmin = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_personasAdmin = new javax.swing.JList<>();
        bt_cerrarTorneo = new javax.swing.JButton();
        bt_marcarGanador = new javax.swing.JButton();
        jd_crearTorneo = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tf_nombreTorneo = new javax.swing.JTextField();
        sp_rondas = new javax.swing.JSpinner();
        bt_crearTorneo = new javax.swing.JButton();
        jd_participante = new javax.swing.JDialog();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        bt_salir = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        bt_unirseTorneo = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        list_torneosParticipante = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        list_torneosCerrados = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        list_torneosGanados = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_username = new javax.swing.JTextField();
        pf_password = new javax.swing.JPasswordField();
        bt_toRegister = new javax.swing.JButton();
        bt_iniciarSesion = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 440));

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Nombre de usuario");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("Contraseña");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));
        jPanel1.add(tf_usernameRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 240, 40));
        jPanel1.add(pf_passwordRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 240, 40));

        buttonGroup1.add(rb_participante);
        rb_participante.setText("Participante");
        jPanel1.add(rb_participante, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, -1, -1));

        buttonGroup1.add(rb_administrador);
        rb_administrador.setText("Administrador");
        jPanel1.add(rb_administrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, -1, -1));

        bt_registrarUsusario.setBackground(new java.awt.Color(255, 51, 51));
        bt_registrarUsusario.setForeground(new java.awt.Color(255, 255, 255));
        bt_registrarUsusario.setText("Crear");
        bt_registrarUsusario.setBorder(null);
        bt_registrarUsusario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_registrarUsusarioMouseClicked(evt);
            }
        });
        jPanel1.add(bt_registrarUsusario, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, 60, 30));

        javax.swing.GroupLayout jd_registroLayout = new javax.swing.GroupLayout(jd_registro.getContentPane());
        jd_registro.getContentPane().setLayout(jd_registroLayout);
        jd_registroLayout.setHorizontalGroup(
            jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
        );
        jd_registroLayout.setVerticalGroup(
            jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jd_admin.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 0, 0));

        bt_salirAdmin.setBackground(new java.awt.Color(0, 0, 255));
        bt_salirAdmin.setForeground(new java.awt.Color(255, 255, 255));
        bt_salirAdmin.setText("Salir");
        bt_salirAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_salirAdminMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(bt_salirAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(406, Short.MAX_VALUE)
                .addComponent(bt_salirAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 460));

        bt_toCrearTorneo.setBackground(new java.awt.Color(0, 0, 255));
        bt_toCrearTorneo.setForeground(new java.awt.Color(255, 255, 255));
        bt_toCrearTorneo.setText("Crear torneo");
        bt_toCrearTorneo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_toCrearTorneoMouseClicked(evt);
            }
        });
        jPanel5.add(bt_toCrearTorneo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Torneos");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));

        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("Personas dentro del torneo");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, -1, -1));

        list_torneosAdmin.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(list_torneosAdmin);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 130, 200));

        list_personasAdmin.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(list_personasAdmin);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 160, 200));

        bt_cerrarTorneo.setBackground(new java.awt.Color(255, 0, 0));
        bt_cerrarTorneo.setForeground(new java.awt.Color(255, 255, 255));
        bt_cerrarTorneo.setText("Cerrar torneo");
        bt_cerrarTorneo.setBorder(null);
        bt_cerrarTorneo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_cerrarTorneoMouseClicked(evt);
            }
        });
        jPanel5.add(bt_cerrarTorneo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 110, 30));

        bt_marcarGanador.setBackground(new java.awt.Color(255, 0, 0));
        bt_marcarGanador.setForeground(new java.awt.Color(255, 255, 255));
        bt_marcarGanador.setText("Marcar Ganador");
        bt_marcarGanador.setBorder(null);
        jPanel5.add(bt_marcarGanador, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 110, 30));

        javax.swing.GroupLayout jd_adminLayout = new javax.swing.GroupLayout(jd_admin.getContentPane());
        jd_admin.getContentPane().setLayout(jd_adminLayout);
        jd_adminLayout.setHorizontalGroup(
            jd_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_adminLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jd_adminLayout.setVerticalGroup(
            jd_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_adminLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jd_crearTorneo.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 440));

        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("Nombre del torneo");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 120, 30));

        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("Rondas");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 50, 30));
        jPanel7.add(tf_nombreTorneo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 180, -1));

        sp_rondas.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jPanel7.add(sp_rondas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, -1, -1));

        bt_crearTorneo.setBackground(new java.awt.Color(0, 0, 255));
        bt_crearTorneo.setForeground(new java.awt.Color(255, 255, 255));
        bt_crearTorneo.setText("Crear Torneo");
        bt_crearTorneo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_crearTorneoMouseClicked(evt);
            }
        });
        jPanel7.add(bt_crearTorneo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, -1, -1));

        javax.swing.GroupLayout jd_crearTorneoLayout = new javax.swing.GroupLayout(jd_crearTorneo.getContentPane());
        jd_crearTorneo.getContentPane().setLayout(jd_crearTorneoLayout);
        jd_crearTorneoLayout.setHorizontalGroup(
            jd_crearTorneoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearTorneoLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jd_crearTorneoLayout.setVerticalGroup(
            jd_crearTorneoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearTorneoLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jd_participante.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(255, 0, 0));

        bt_salir.setBackground(new java.awt.Color(0, 0, 255));
        bt_salir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bt_salir.setForeground(new java.awt.Color(255, 255, 255));
        bt_salir.setText("Salir");
        bt_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_salirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(bt_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(406, Short.MAX_VALUE)
                .addComponent(bt_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 460));

        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("Torneos disponibles");
        jPanel9.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, -1));

        jLabel11.setForeground(new java.awt.Color(0, 0, 255));
        jLabel11.setText("Torneos cerrados");
        jPanel9.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, -1));

        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("Torneos ganados");
        jPanel9.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, -1, -1));

        bt_unirseTorneo.setBackground(new java.awt.Color(255, 0, 0));
        bt_unirseTorneo.setForeground(new java.awt.Color(255, 255, 255));
        bt_unirseTorneo.setText("Unirse a torneo");
        bt_unirseTorneo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_unirseTorneoMouseClicked(evt);
            }
        });
        jPanel9.add(bt_unirseTorneo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, -1, -1));

        list_torneosParticipante.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(list_torneosParticipante);

        jPanel9.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 130, 200));

        list_torneosCerrados.setModel(new DefaultListModel());
        jScrollPane4.setViewportView(list_torneosCerrados);

        jPanel9.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 120, 200));

        list_torneosGanados.setModel(new DefaultListModel());
        jScrollPane5.setViewportView(list_torneosGanados);

        jPanel9.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 110, 200));

        javax.swing.GroupLayout jd_participanteLayout = new javax.swing.GroupLayout(jd_participante.getContentPane());
        jd_participante.getContentPane().setLayout(jd_participanteLayout);
        jd_participanteLayout.setHorizontalGroup(
            jd_participanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_participanteLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jd_participanteLayout.setVerticalGroup(
            jd_participanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_participanteLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Nombre de Usuario");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Contraseña");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 60, -1));
        jPanel2.add(tf_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 230, 40));
        jPanel2.add(pf_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 220, 50));

        bt_toRegister.setBackground(new java.awt.Color(0, 0, 204));
        bt_toRegister.setForeground(new java.awt.Color(255, 255, 255));
        bt_toRegister.setText("Registrar");
        bt_toRegister.setBorder(null);
        bt_toRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_toRegisterMouseClicked(evt);
            }
        });
        jPanel2.add(bt_toRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 70, 30));

        bt_iniciarSesion.setBackground(new java.awt.Color(255, 0, 0));
        bt_iniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        bt_iniciarSesion.setText("Iniciar sesión");
        bt_iniciarSesion.setBorder(null);
        bt_iniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_iniciarSesionMouseClicked(evt);
            }
        });
        jPanel2.add(bt_iniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 450, 90, 30));

        jPanel3.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 530));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/unitec color.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_toRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_toRegisterMouseClicked
        this.setVisible(false);
        jd_registro.pack();
        jd_registro.setLocationRelativeTo(null);
        jd_registro.setVisible(true);
    }//GEN-LAST:event_bt_toRegisterMouseClicked

    private void bt_toCrearTorneoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_toCrearTorneoMouseClicked
        jd_admin.dispose();
        jd_crearTorneo.pack();
        jd_crearTorneo.setLocationRelativeTo(null);
        jd_crearTorneo.setVisible(true);
    }//GEN-LAST:event_bt_toCrearTorneoMouseClicked

    private void bt_registrarUsusarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_registrarUsusarioMouseClicked
       
        if (rb_participante.isSelected()) {
            User nuevoUsuario = new Participante(tf_usernameRegister.getText(), pf_passwordRegister.getText());
            administradorUser admin = new administradorUser("./participante.lj");
            admin.cargarArchivo();
            admin.setUser(nuevoUsuario);
            admin.escribirArchivo();
            tf_usernameRegister.setText("");
            pf_passwordRegister.setText("");
            JOptionPane.showMessageDialog(jd_registro, "Participante registrado exitosamente.");
        } else if (rb_administrador.isSelected()) {
            User nuevoAdministrador = new Admin(tf_usernameRegister.getText(), pf_passwordRegister.getText());
            administradorUser admin = new administradorUser("./admin.lj");
            admin.cargarArchivo();
            admin.setUser(nuevoAdministrador);
            admin.escribirArchivo();
            tf_usernameRegister.setText("");
            pf_passwordRegister.setText("");
            JOptionPane.showMessageDialog(jd_registro, "Administrador registrado exitosamente.");
        }else{
            JOptionPane.showMessageDialog(jd_registro, "Elija si el usuario es participante o administrador. ");
        }
    }//GEN-LAST:event_bt_registrarUsusarioMouseClicked

    private void bt_crearTorneoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_crearTorneoMouseClicked
       Torneo nuevoTorneo = new Torneo(tf_nombreTorneo.getText(), (int) sp_rondas.getValue());
       nuevoTorneo.setAbierto(true);
       adminTorneo admin = new adminTorneo("./torneos.lj");
       admin.cargarArchivo();
       admin.getTorneo().add(nuevoTorneo);
       admin.escribirArchivo();
       JOptionPane.showMessageDialog(jd_crearTorneo, "Torneo agregado exitosamente");
       tf_nombreTorneo.setText("");
       sp_rondas.setValue(0);
       
       DefaultListModel modelo = (DefaultListModel) list_torneosAdmin.getModel();
       modelo.addElement(nuevoTorneo);
       list_torneosAdmin.setModel(modelo);
       
       DefaultListModel modeloParticipantes = (DefaultListModel) list_torneosParticipante.getModel();
       modeloParticipantes.addElement(nuevoTorneo);
       list_torneosParticipante.setModel(modeloParticipantes);
       
       jd_crearTorneo.dispose();
       jd_admin.pack();
       jd_admin.setLocationRelativeTo(null);
       jd_admin.setVisible(true);
    }//GEN-LAST:event_bt_crearTorneoMouseClicked

    private void bt_iniciarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_iniciarSesionMouseClicked
        boolean encontrado = false;

        administradorUser admin = new administradorUser("./admin.lj");
        admin.cargarArchivo();
        for (Object users : admin.getUser()) {
            if (tf_username.getText().equals(((Admin) users).getNombre()) && pf_password.getText().equals(((Admin) users).getContraseña())) {
                //aqui se hace el dispose y se despligue la ventana del admin.
                this.setVisible(false);
                jd_admin.pack();
                jd_admin.setLocationRelativeTo(null);
                jd_admin.setVisible(true);
                tf_username.setText("");
                pf_password.setText("");
                encontrado = true;
                
                
                DefaultListModel listas = (DefaultListModel) list_torneosAdmin.getModel();
                   adminTorneo admin2 = new adminTorneo("./torneo.lj");
                   for (Object admin4 : admin2.getTorneo()) {  
                       listas.addElement(admin4);
                       list_torneosAdmin.setModel(listas);
                   }
            }
            
        }
        

        if (!encontrado) {
            administradorUser adminUsers = new administradorUser("./participante.lj");
            adminUsers.cargarArchivo();
            for (Object users : adminUsers.getUser()) {
                if (tf_username.getText().equals(((Participante) users).getNombre())
                    && pf_password.getText().equals(((Participante) users).getContraseña())) {
                    this.setVisible(false);
                    jd_participante.pack();
                    jd_participante.setLocationRelativeTo(null);
                    jd_participante.setVisible(true);
                    tf_username.setText("");
                    pf_password.setText("");
                    encontrado = true;
                }
                
                DefaultListModel lista2 = (DefaultListModel) list_torneosParticipante.getModel();
                       adminTorneo admin2 = new adminTorneo("./torneo.jl");
                       for (Object admin1 : admin2.getTorneo()) {
                           lista2.addElement(admin1);
                           list_torneosParticipante.setModel(lista2);  
                       }
            }
        }
        
        if (!encontrado) {
            JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrecto.");
        }
    }//GEN-LAST:event_bt_iniciarSesionMouseClicked

    private void bt_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_salirMouseClicked
        jd_participante.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_bt_salirMouseClicked

    private void bt_salirAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_salirAdminMouseClicked
        jd_admin.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_bt_salirAdminMouseClicked

    private void bt_cerrarTorneoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_cerrarTorneoMouseClicked
        if (list_torneosAdmin.getSelectedIndex() >= 0) {
            DefaultListModel listaActualizada = (DefaultListModel) list_torneosAdmin.getModel();
            listaActualizada.remove(list_torneosAdmin.getSelectedIndex());
            list_torneosAdmin.setModel(listaActualizada);

            DefaultListModel torneos = (DefaultListModel) list_torneosCerrados.getModel();
            torneos.addElement(listaActualizada);
            list_torneosCerrados.setModel(torneos);
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona un torneo para finalizarlo");
        }
    }//GEN-LAST:event_bt_cerrarTorneoMouseClicked

    private void bt_unirseTorneoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_unirseTorneoMouseClicked
       if(list_torneosAdmin.getSelectedIndex() >= 0){
           JOptionPane.showMessageDialog(jd_admin, "Ingresado correctamente");
       }else{
           JOptionPane.showMessageDialog(jd_admin, "No se pudo ingresar al torneo.");
       }
    }//GEN-LAST:event_bt_unirseTorneoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WorkingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WorkingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WorkingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WorkingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WorkingGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cerrarTorneo;
    private javax.swing.JButton bt_crearTorneo;
    private javax.swing.JButton bt_iniciarSesion;
    private javax.swing.JButton bt_marcarGanador;
    private javax.swing.JButton bt_registrarUsusario;
    private javax.swing.JButton bt_salir;
    private javax.swing.JButton bt_salirAdmin;
    private javax.swing.JButton bt_toCrearTorneo;
    private javax.swing.JButton bt_toRegister;
    private javax.swing.JButton bt_unirseTorneo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JDialog jd_admin;
    private javax.swing.JDialog jd_crearTorneo;
    private javax.swing.JDialog jd_participante;
    private javax.swing.JDialog jd_registro;
    private javax.swing.JList<String> list_personasAdmin;
    private javax.swing.JList<String> list_torneosAdmin;
    private javax.swing.JList<String> list_torneosCerrados;
    private javax.swing.JList<String> list_torneosGanados;
    private javax.swing.JList<String> list_torneosParticipante;
    private javax.swing.JPasswordField pf_password;
    private javax.swing.JPasswordField pf_passwordRegister;
    private javax.swing.JRadioButton rb_administrador;
    private javax.swing.JRadioButton rb_participante;
    private javax.swing.JSpinner sp_rondas;
    private javax.swing.JTextField tf_nombreTorneo;
    private javax.swing.JTextField tf_username;
    private javax.swing.JTextField tf_usernameRegister;
    // End of variables declaration//GEN-END:variables
}
